# Generated by Django 4.2.30 on 2026-05-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentgallery',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='principal',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
